# Generated by Django 5.1.7 on 2025-03-29 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
