# Generated by Django 5.1.7 on 2025-03-29 03:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_location', models.CharField(max_length=100)),
                ('class_time', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('current_students', models.IntegerField()),
                ('current_space', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=False), blank=True, default=list, size=None)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_info', to='demos.lecture')),
            ],
        ),
    ]
